name:Russian Ruble Token  
symbol: RUBT
description: A digital token pegged 1:1 to the Russian Ruble. Backed by fiat deposits via SBP.
decimals: 2
image: https://moccasin-added-dove-152.mypinata.cloud/ipfs/bafkreidt2wxuoy2oywmynaeld7xk2tvwtha2zfwj6yrwiebuw6an3mgqam
address: EQCfQJIfduCv65T0udDaPGiHBj_0JtUG055dgZWfKG-3gwuz